# Generated by Django 5.0.2 on 2024-03-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('calorias', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
